env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  import/prefer-default-export: 0
  eol-last: 0
  indent: 1
  prefer-template: 0
  operator-linebreak: 0
  comma-dangle: 0
  consistent-return: 0