env:
  node: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  linebreak-style: 0
  quotes: 0
  import/prefer-default-export: 0
  eol-last: 0
  indent: 1
  prefer-template: 0